name: google_api_availability_android
description: An Android implementation for the google_api_availability plugin.
repository: https://github.com/baseflow/flutter-google-api-availability/tree/main/google_api_availability_android
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.1

flutter:
  plugin:
    implements: google_api_availability
    platforms:
      android:
        package: com.baseflow.googleapiavailability
        pluginClass: GoogleApiAvailabilityPlugin
        dartPluginClass: GoogleApiAvailabilityAndroid

dependencies:
  flutter:
    sdk: flutter
  google_api_availability_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.3.2

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"
