name: Ask for help
description: You have a question about the Google API availability plugin and are looking for help.
title: "[Question]: "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        We are happy to help you out!
        To help you effectively, we require some information. This will allow us to quickly understand your question.
  - type: checkboxes
    attributes:
      label: Please check the following before submitting a new issue.
      options:
        - label: I have searched the [existing issues](https://github.com/baseflow/flutter-google-api-availability/issues).
          required: true
        - label: I have carefully [read the documentation](https://github.com/baseflow/flutter-google-api-availability/blob/main/google_api_availability/README.md).
          required: true
  - type: textarea
    attributes:
      label: Your question
      description: |
        Please describe your question as detailed as possible.

        Please attach something to help us understand your question:
         * code samples
         * images
         * videos
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Please specify which version of the plugin are you currently using.
      placeholder: ex. 1.2.3
    validations:
      required: true
