name: google_api_availability_example
description: Demonstrates how to use the google_api_availability plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_availability_android:
    path: ../
  google_api_availability_platform_interface: ^1.0.1

dev_dependencies:
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
