name: google_api_availability_example
description: Demonstrates how to use the google_api_availability plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_availability:
    path: ../

dev_dependencies:
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
