name: google_api_availability
description: A Flutter plugin to check the availability of Google Play Services on an Android device.
version: 5.0.0
homepage: https://github.com/baseflowit/flutter-google-api-availability

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  google_api_availability_android: ^1.0.0+1
  google_api_availability_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.4

flutter:
  plugin:
    platforms:
      android:
        default_package: google_api_availability_android
